### ISSUE TITLE
Error when a policy has a rules that targets `*`  for apiGroups

### ISSUE THREAD

**Issue by viccuad** [kubewarden/audit-scanner#168]
### Current wrong behaviour

Policies targetting `resources: ["*"]` are valid, yet skipped by the Audit Scanner for now, [see docs](https://docs.kubewarden.io/explanations/audit-scanner/limitations#usage-of--by-policies).

Audit scanner should only collect resources per policy for those policies explicitly targetting `operations: ["CREATE"]`, and for those policies that don't list `resources: ["*"]`.

Still, when a policy is defined with a rule such as:
  ```yml
  rules:
  - apiGroups:
    - "*"
    apiVersions:
    - "*"
    operations:
    - '*'
    resources:
    - "*"
```

The audit scanner crashes with the following reason:
```
{"level":"fatal","error":"the server could not find the requested resource","time":"2024-01-04T08:32:37Z","message":"Error on cmd.Execute()"}
```

### Expected behaviour

The policy should be skipped by the audit scanner, with the following debug message:
```
{"level":"debug","policy":"foo","backgroundAudit":true,"active":true,"create":false,"time":"2024-01-04T10:52:12+01:00","message":"not auditable policy, skipping!"}
```

### Workaround

Separate the rules into several array entries, for example:
```yml
rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - replicationcontrollers
[...]
```
