### ISSUE TITLE
Audit scanner errors out instead of skipping `*` policies

### ISSUE THREAD

**Issue by kravciak** [kubewarden/audit-scanner#233]
The example is safelabels policy - if I leave `*` defaults in rules audit scanner jobs fail with error.
As a side-effect cluster has many `Error` pods from failed cronjobs which are not cleaned automatically.

```yaml
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: starlabels
  namespace: ''
  annotations:
    artifacthub/pkg: safe-labels/safe-labels/0.1.14
spec:
  backgroundAudit: true
  policyServer: default
  module: ghcr.io/kubewarden/policies/safe-labels:v0.1.14
  rules:
    - apiGroups:
        - '*'
      apiVersions:
        - '*'
      resources:
        - '*'
      operations:
        - CREATE
        - UPDATE
  mutating: false
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - calico-system
          - cattle-alerting
          - cattle-fleet-local-system
          - cattle-fleet-system
          - cattle-global-data
          - cattle-global-nt
          - cattle-impersonation-system
          - cattle-istio
          - cattle-logging
          - cattle-pipeline
          - cattle-prometheus
          - cattle-system
          - cert-manager
          - ingress-nginx
          - kube-node-lease
          - kube-public
          - kube-system
          - rancher-operator-system
          - security-scan
          - tigera-operator
    matchLabels: {}
  settings:
    description: null
    constrained_labels: {}
    denied_labels:
      - qqq
    mandatory_labels:
      - aaa
  contextAwareResources: []
  mode: monitor

```

```bash
~ k logs -n cattle-kubewarden-system audit-scanner-28522836-ggpkr
{"level":"info","time":"2024-03-25T12:36:00Z","message":"clusterwide resources scan started"}
{"level":"fatal","error":"no matches for */*, Resource=*","time":"2024-03-25T12:36:00Z","message":"Error on cmd.Execute()"}
```
