### ISSUE TITLE
Reports are not updated after last policy removal

### ISSUE THREAD

**Issue by kravciak** [kubewarden/audit-scanner#263]
I have a CA policy that produces audit-report on the namespace.
When I delete this policy audit report on namespace is not removed / retriggered, leaving behind clusterpolicyreport.

## To reproduce:

- install Kubewarden with recommended policies
- create safe-labels policy with following settings
```yaml
apiVersion: policies.kubewarden.io.v1
kind: ClusterAdmissionPolicy
metadata:
  name: safelabels
spec:
  backgroundAudit: true
  policyServer: default
  module: ghcr.io/kubewarden/policies/safe-labels:v0.1.14
  rules:
    - apiGroups:
        - ''
      apiVersions:
        - ''
      resources:
        - 'namespaces'
      operations:
        - CREATE
        - UPDATE
  settings:
    constrained_labels: {}
    denied_labels:
      - qqq
```
- add denied label to default namespace `kubectl label ns default qqq=1`
- trigger audit scan (at this point clusterpolicyreport for default namespace with 1 FAIL is created as expected)
- delete `safelabels` policy and trigger audit scan

#### Current state:
Clusterpolicyreport for default namespace with 1 FAIL is not removed, UI points to non-existent policy

#### Expexted state:
Clusterpolicyreport results from non-existent policies are cleaned
