### ISSUE TITLE
Audit Scanner fails completely with typo in policy

### ISSUE THREAD

**Issue by Martin-Weiss** [kubewarden/audit-scanner#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using this policy (example from https://artifacthub.io/packages/kubewarden/verify-image-signatures/verify-image-signatures)

```
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: verify-image-signatures
spec:
  module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.1.7
  rules:
  - apiGroups: ["", "apps", "batch"]
    apiVersions: ["v1"]
    resources: ["pods", "deployments", "statefulsets", "replicationcontrollers", "jobs", "cronjobs"]
    operations:
    - CREATE
    - UPDATE
  mutating: true
  settings:
    signatures:
    - image: "*"
      githubActions:
        owner: "kubewarden"
        repo: "app-example" 
```

 with kubewarden-controller-2.1.0 kubewarden-crds-1.5.1 kubewarden-defaults-2.0.3  ends up in audit-scanner failing fatal with the following

```
kubectl -n kubewarden logs audit-scanner-28655400-49zwv 
{"level":"info","RunUID":"b87b30fc-5633-42c8-ab21-bf585d6826a6","time":"2024-06-25T14:00:01Z","message":"clusterwide resources scan started"}
{"level":"fatal","error":"no matches for apps/v1, Resource=pods","time":"2024-06-25T14:00:02Z","message":"Error on cmd.Execute()"}
```

### Expected Behavior

Audit scanner must not fail completely if a policy is not perfect ok.

### Steps To Reproduce

See above - more details here:https://github.com/Martin-Weiss/rancher-fleet/tree/bb68ca7288b42dcc7ddea27d5ffabde7fe241d22/kubewarden

### Environment

```markdown
rke2 1.28.10 x86_64 on linux
```
