### ISSUE TITLE
Errored policies with exceeded deadline are being recorded as `fail` instead

### ISSUE THREAD

**Issue by viccuad** [kubewarden/audit-scanner#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With a policy that errors. For example because it exceeds the deadline, such as `ghcr.io/kubewarden/policies/user-group-psp:v0.6.0` with `settings.validate_container_image_configuration: true`:

```yaml
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  annotations:
    io.kubewarden.policy.category: PSP
    io.kubewarden.policy.severity: medium
    meta.helm.sh/release-name: kubewarden-defaults
    meta.helm.sh/release-namespace: kubewarden
  name: do-not-run-as-root
spec:
  backgroundAudit: true
  mode: monitor
  module: ghcr.io/kubewarden/policies/user-group-psp:v0.6.0
  mutating: true
  policyServer: default
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  settings:
    run_as_group:
      rule: RunAsAny
    run_as_user:
      rule: MustRunAsNonRoot
    supplemental_groups:
      rule: RunAsAny
    validate_container_image_configuration: true
```

The run of this policy for `audit` in the policy-server ends in error:

```
2024-07-30T11:42:05.815220Z ERROR request{method=POST uri=https://policy-server-default.kubewarden.svc:8443/audit/clusterwide-do-not-run-as-root version=HTTP/2.0}:audit{host="policy-server-default-5545c65fb9-zkqhk" policy_id="clusterwide-do-not-run-as-root" kind="Pod" kind_group="" kind_version="v1" name="nginx-with-se
crets" namespace="default" operation="CREATE" request_uid="24c1e904-110c-46da-b106-2625159a5aca" resource="Pod" resource_group="" resource_version="v1" subresource=""}:validate{self=PolicyEvaluator { runtime: "wapc" } settings={"run_as_group": Object {"rule": String("RunAsAny")}, "run_as_user": Object {"rule": String("
MustRunAsNonRoot")}, "supplemental_groups": Object {"rule": String("RunAsAny")}, "validate_container_image_configuration": Bool(true)}}: wasmtime_provider: Failure invoking guest module handler: error while executing at wasm backtrace:
    0: 0x174348 - user_group_psp.wasm!__rust_alloc
    1: 0x159fe9 - user_group_psp.wasm!wapc_guest::protocol::host_call::hd7c0336615a6a914
    2: 0xec82c - user_group_psp.wasm!kubewarden_policy_sdk::host_capabilities::oci::get_manifest_and_config::h803fae37c19f4dec
    3: 0x4ded9 - user_group_psp.wasm!user_group_psp::enforce_container_security_policies::h4214b9038ed52ddd
    4: 0x246fa - user_group_psp.wasm!user_group_psp::validate::h1b0f7d0e060e55cd
    5: 0xbb0db - user_group_psp.wasm!__guest_call
    6: 0x1755cc - user_group_psp.wasm!__guest_call.command_export

Caused by:
    wasm trap: interrupt
2024-07-30T11:42:05.815311Z ERROR request{method=POST uri=https://policy-server-default.kubewarden.svc:8443/audit/clusterwide-do-not-run-as-root version=HTTP/2.0}:audit{host="policy-server-default-5545c65fb9-zkqhk" policy_id="clusterwide-do-not-run-as-root" kind="Pod" kind_group="" kind_version="v1" name="nginx-with-se
crets" namespace="default" operation="CREATE" request_uid="24c1e904-110c-46da-b106-2625159a5aca" resource="Pod" resource_group="" resource_version="v1" subresource=""}:validate{self=PolicyEvaluator { runtime: "wapc" } settings={"run_as_group": Object {"rule": String("RunAsAny")}, "run_as_user": Object {"rule": String("
MustRunAsNonRoot")}, "supplemental_groups": Object {"rule": String("RunAsAny")}, "validate_container_image_configuration": Bool(true)}}: policy_evaluator::runtimes::wapc::runtime: waPC communication error error="Guest call failure: guest code interrupted, execution deadline exceeded"
2024-07-30T11:42:05.815825Z  INFO request{method=POST uri=https://policy-server-default.kubewarden.svc:8443/audit/clusterwide-do-not-run-as-root version=HTTP/2.0}:audit{host="policy-server-default-5545c65fb9-zkqhk" policy_id="clusterwide-do-not-run-as-root" kind="Pod" kind_group="" kind_version="v1" name="demo-capabili
ties" namespace="default" operation="CREATE" request_uid="1f5b66c7-c29a-4359-b5f4-b7d49c470829" resource="Pod" resource_group="" resource_version="v1" subresource=""}:validate{self=PolicyEvaluator { runtime: "wapc" } settings={"run_as_group": Object {"rule": String("RunAsAny")}, "run_as_user": Object {"rule": String("M
ustRunAsNonRoot")}, "supplemental_groups": Object {"rule": String("RunAsAny")}, "validate_container_image_configuration": Bool(true)}}: policy_evaluator::runtimes::wapc::runtime: wapc_host reset performed after timeout protection was triggered
2024-07-30T11:42:05.816028Z  INFO request{method=POST uri=https://policy-server-default.kubewarden.svc:8443/audit/clusterwide-do-not-run-as-root version=HTTP/2.0}:audit{host="policy-server-default-5545c65fb9-zkqhk" policy_id="clusterwide-do-not-run-as-root" kind="Pod" kind_group="" kind_version="v1" name="nginx-with-se
crets" namespace="default" operation="CREATE" request_uid="24c1e904-110c-46da-b106-2625159a5aca" resource="Pod" resource_group="" resource_version="v1" subresource=""}:validate{self=PolicyEvaluator { runtime: "wapc" } settings={"run_as_group": Object {"rule": String("RunAsAny")}, "run_as_user": Object {"rule": String("
MustRunAsNonRoot")}, "supplemental_groups": Object {"rule": String("RunAsAny")}, "validate_container_image_configuration": Bool(true)}}: policy_evaluator::runtimes::wapc::runtime: wapc_host reset performed after timeout protection was triggered

```

Yet the PolicyReportResult is saved as `fail` instead of `error`.
Excerpt from the PolicyReport matching the specific Pod:

```yaml
- category: PSP
  message: 'internal server error: Guest call failure: guest code interrupted, execution
    deadline exceeded'
  policy: clusterwide-do-not-run-as-root
  properties:
    mutating: "true"
    policy-name: do-not-run-as-root
    policy-resource-version: "2081"
    policy-uid: ec20518f-3459-448c-bb7e-345deaf54f68
  resourceSelector: {}
  result: fail
  scored: true
  severity: info
  source: kubewarden
  timestamp:
    nanos: 0
    seconds: 1722337206
```

On the audit-scanner logs, the policy run, for `do-not-run-as-root`, is recorded as `fail` instead of `error`:
```
{"level":"debug","response":{"uid":"3b42be32-3bb8-4ada-b20f-187a73b650bb","policy":"do-not-run-as-root","resource":"nginx-privileged","allowed":false},"time":"2024-07-30T11:12:03Z","message":"audit review response"}
{"level":"debug","response":{"uid":"4aad92c5-5020-403d-beb7-97ba66523a97","policy":"do-not-run-as-root","resource":"show-capabilities-28705631-hwcjw","allowed":false},"time":"2024-07-30T11:12:03Z","message":"audit review response"}
{"level":"debug","response":{"uid":"d0a337d1-fc50-4204-a139-4310e4ba3911","policy":"do-not-run-as-root","resource":"show-capabilities-28705630-59fvz","allowed":false},"time":"2024-07-30T11:12:03Z","message":"audit review response"}
{"level":"debug","dict":{},"report-name":"4aad92c5-5020-403d-beb7-97ba66523a97","report-version":"","resource-name":"show-capabilities-28705631-hwcjw","resource-namespace":"default","resource-version":"4159","time":"2024-07-30T11:12:03Z","message":"PolicyReport created"}
{"level":"debug","dict":{},"report-name":"d0a337d1-fc50-4204-a139-4310e4ba3911","report-version":"","resource-name":"show-capabilities-28705630-59fvz","resource-namespace":"default","resource-version":"4037","time":"2024-07-30T11:12:03Z","message":"PolicyReport created"}
{"level":"debug","dict":{},"report-name":"3b42be32-3bb8-4ada-b20f-187a73b650bb","report-version":"","resource-name":"nginx-privileged","resource-namespace":"default","resource-version":"1299","time":"2024-07-30T11:12:03Z","message":"PolicyReport updated"}
{"level":"debug","response":{"uid":"1f5b66c7-c29a-4359-b5f4-b7d49c470829","policy":"do-not-run-as-root","resource":"demo-capabilities","allowed":false},"time":"2024-07-30T11:12:05Z","message":"audit review response"}
{"level":"debug","response":{"uid":"24c1e904-110c-46da-b106-2625159a5aca","policy":"do-not-run-as-root","resource":"nginx-with-secrets","allowed":false},"time":"2024-07-30T11:12:05Z","message":"audit review response"}
{"level":"debug","dict":{},"report-name":"1f5b66c7-c29a-4359-b5f4-b7d49c470829","report-version":"","resource-name":"demo-capabilities","resource-namespace":"default","resource-version":"1283","time":"2024-07-30T11:12:05Z","message":"PolicyReport updated"}
{"level":"debug","dict":{},"report-name":"24c1e904-110c-46da-b106-2625159a5aca","report-version":"","resource-name":"nginx-with-secrets","resource-namespace":"default","resource-version":"1291","time":"2024-07-30T11:12:05Z","message":"PolicyReport updated"}
```

### Expected Behavior

The PolicyReportResult should be of `result: error`

### Steps To Reproduce

Start a run that exercises the mentioned policy, or one that errors.

### Environment

```markdown
$ helm ls -A
NAME                    NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                           APP VERSION
cert-manager            cert-manager    2               2024-07-30 12:53:14.229617236 +0200 CEST        deployed        cert-manager-v1.15.1            v1.15.1
fakeworkload            default         1               2024-07-30 12:51:14.845709897 +0200 CEST        deployed        fakeWorkLoad-0.1.0
kubewarden-controller   kubewarden      2               2024-07-30 12:53:21.364885061 +0200 CEST        deployed        kubewarden-controller-2.3.0-rc3 v1.15.0-rc3
kubewarden-crds         kubewarden      2               2024-07-30 12:53:19.045913932 +0200 CEST        deployed        kubewarden-crds-1.7.0-rc3       v1.15.0-rc3
kubewarden-defaults     kubewarden      2               2024-07-30 12:54:16.711639285 +0200 CEST        deployed        kubewarden-defaults-2.2.0-rc3   v1.15.0-rc3
```

With fakeworkload from https://github.com/kubewarden/kubecon-24-eu-kubewarden/blob/main/helmfile.d/fakeWorkLoad.yaml
