### ISSUE TITLE
API resource forbidden, unknown GVK or ServiceAccount lacks permissions

### ISSUE THREAD

**Issue by mueller-ma** [kubewarden/audit-scanner#520]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The audit scanner crashes right after it started with the following log:

````
$ kubectl logs audit-scanner-29097060-f28j6
{"level":"info","RunUID":"bf08ce22-980d-46a5-a64c-402bceb34b75","time":"2025-04-28T07:00:34Z","message":"clusterwide resources scan started"}
{"level":"info","dict":{"policies-to-evaluate":1,"policies-skipped":1,"policies-errored":0,"parallel-resources-audits":50},"time":"2025-04-28T07:00:34Z","message":"cluster admission policies count"}
{"level":"warn","dict":{"resource-GVK":"admissionregistration.k8s.io/v1, Resource=validatingwebhookconfigurations","ns":""},"time":"2025-04-28T07:00:34Z","message":"API resource forbidden, unknown GVK or ServiceAccount lacks permissions"}
{"level":"fatal","error":"validatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User \"system:serviceaccount:kubewarden:audit-scanner\" cannot list resource \"validatingwebhookconfigurations\" in API group \"admissionregistration.k8s.io\" at the cluster scope","time":"2025-04-28T07:00:34Z","message":"Error on cmd.Execute()"}
````

### Expected Behavior

I expect the service account to have the required permissions. Is this something I need to configure via helm values or is this a bug in kubewarden?

### Environment

```markdown
- OS: Linux
- Architecture: amd64
- Kubernetes: v1.29.15+rke2r1

$ helm list
NAME                    NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                           APP VERSION
kubewarden-controller   kubewarden      2               2025-04-17 14:58:58.396458342 +0200 CEST        deployed        kubewarden-controller-5.1.0     v1.23.0
kubewarden-crds         kubewarden      8               2025-04-07 09:01:05.148423516 +0200 CEST        deployed        kubewarden-crds-1.15.0          v1.23.0
kubewarden-defaults     kubewarden      1               2025-04-17 14:21:15.586763902 +0200 CEST        deployed        kubewarden-defaults-3.1.0       v1.23.0
```

Values of kubewarden-controller chart:
```
nodeSelector:
node-role.kubernetes.io/control-plane: "true"
replicas: 2
auditScanner:
policyReporter: true
parallelResources: 50
policy-reporter:
ui:
  enabled: true
  ingress:
	enabled: true
	hosts:
	  - host: example.com
		paths:
		  - path: /
			pathType: ImplementationSpecific
```
