### ISSUE TITLE
Audit-scanner panics when ServiceAccount perms aren't enough

### ISSUE THREAD

**Issue by viccuad** [kubewarden/audit-scanner#68]
While testing the ClusterPolicyReport generation,
With a PV (a clusterwide resource) with a label:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
  labels:
    cost-center: "123"
spec:
  capacity:
    storage: 1M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/disks/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
                - example-node
```
And a a safe labels policy:
```
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  annotations:
    io.kubewarden.policy.category: Resource validation
    io.kubewarden.policy.severity: low
  name: safe-labels
spec:
  module: registry://ghcr.io/kubewarden/policies/safe-labels:v0.1.13
  settings:
    denied_labels:
      - cost-center
  mode: monitor
  rules:
    - apiGroups:
        - "*"
      apiVersions:
        - "*"
      resources:
        - "PersistentVolume" # changed from *
      operations:
        - CREATE
        - UPDATE
  mutating: false
  backgroundAudit: true # changed
```

The audit-scanner jobs error correctly as they can't access the PV, and then panic:
```
{"level":"info","time":"2023-07-14T16:26:35Z","message":"cluster wide scan started"}
{"level":"warn","time":"2023-07-14T16:26:35Z","message":"API resource (/v1, Resource=PersistentVolume) not found"}
{"level":"info","time":"2023-07-14T16:26:35Z","message":"scan finished"}
{"level":"info","dict":{"report name":"polr-clusterwide","report ns":"","summary":"{\"pass\":0,\"fail\":0,\"warn\":0,\"error\":0,\"skip\":0}"},"time":"2023-07-14T16:26:35Z","message":"updated ClusterPolicyReport"}
{"level":"info","time":"2023-07-14T16:26:35Z","message":"all-namespaces scan started"}
{"level":"info","namespace":"cert-manager","time":"2023-07-14T16:26:35Z","message":"namespace scan started"}
{"level":"info","namespace":"cert-manager","dict":{"policies to evaluate":2,"policies skipped":0},"time":"2023-07-14T16:26:35Z","message":"policy count"}
{"level":"error","error":"PersistentVolume is forbidden: User \"system:serviceaccount:kubewarden:audit-scanner\" cannot list resource \"PersistentVolume\" in API group \"\" in the namespace \"cert-manager\"","ns":"cert-manager","time":"2023-07-14T16:26:35Z","message":"error scanning namespace"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16134d0]

goroutine 1 [running]:
github.com/kubewarden/audit-scanner/internal/scanner.(*Scanner).ScanAllNamespaces(0xc0004e83f0)
    /workspace/internal/scanner/scanner.go:138 +0x1f0
github.com/kubewarden/audit-scanner/cmd.startScanner({0x0?, 0xc000530f80?}, 0x60?, {0x1c72690, 0xc0004e83f0})
    /workspace/cmd/root.go:105 +0xb7
github.com/kubewarden/audit-scanner/cmd.glob..func1(0x28b3ee0?, {0x1a1e3b4?, 0x19?, 0x19?})
    /workspace/cmd/root.go:74 +0x186
github.com/spf13/cobra.(*Command).execute(0x28b3ee0, {0xc0001024f0, 0x19, 0x19})
    /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x28b3ee0)
    /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
    /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/kubewarden/audit-scanner/cmd.Execute()
    /workspace/cmd/root.go:82 +0x25
main.main()
    /workspace/main.go:8 +0x17
Stream closed EOF for kubewarden/audit-scanner-28155861-4d2mb (audit-scanner)
```

We shouldn't panic if we can't access a resource, but skip it from the list.
